# Generated by Django 6.0.3 on 2026-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('volunteer', 'Volunteer'), ('super_admin', 'Super Admin'), ('coordinator', 'Coordinator')], max_length=20, null=True),
        ),
    ]
