# Generated by Django 5.0.14 on 2026-04-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_profile_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
