# Generated by Django 5.0.14 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_profile_complete_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
