# Generated by Django 6.0.3 on 2026-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('organizer', 'Organizer'), ('participant', 'Participant'), ('super_admin', 'Super Admin')], max_length=20, null=True),
        ),
    ]
