"""
Django settings for syntra project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR.parent / 'frontend'
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qb&_!-xcp+2t)2oy((=_1olwzy3!z0&nunou2n-@wf_wjdhv)d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SOCIAL_AUTH_BASE_URL = os.getenv('SOCIAL_AUTH_BASE_URL', 'http://localhost:8000').strip().rstrip('/')
SOCIAL_AUTH_BASE_HOST = urlparse(SOCIAL_AUTH_BASE_URL).netloc

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]
if SOCIAL_AUTH_BASE_HOST:
    ALLOWED_HOSTS.append(SOCIAL_AUTH_BASE_HOST.split(':', 1)[0])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'django_celery_beat',
    'super_admin',
    'judge',
    'organizer',
    'participant',
    'volunteers',
    'accounts',
    'api',
    'core',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.UserFlowMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/accounts/social-redirect/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SyntraSocialAccountAdapter'
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'prompt': 'select_account',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', '').strip(),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', '').strip(),
        }
    },
    'github': {
        'SCOPE': ['user:email'],
        'APP': {
            'client_id': os.getenv('GITHUB_CLIENT_ID', '').strip(),
            'secret': os.getenv('GITHUB_CLIENT_SECRET', '').strip(),
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ── Celery ────────────────────────────────────────────────────────────────────
# Broker + result backend — both point at Redis.
# Set REDIS_URL in your .env file: REDIS_URL=redis://127.0.0.1:6379/0
CELERY_BROKER_URL     = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

# Use the same timezone as Django so Beat fires at the right wall-clock time.
CELERY_TIMEZONE = 'Asia/Kolkata'

# Serialisation — JSON keeps things portable and human-readable.
CELERY_TASK_SERIALIZER   = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT    = ['json']

# Best-practice: always acknowledge a task *after* it's executed, not before.
CELERY_TASK_ACKS_LATE = True

# Prevent a single hanging task from hogging a worker process forever.
CELERY_TASK_SOFT_TIME_LIMIT = 60   # seconds — raises SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT      = 90   # hard kill after 90 s

# Beat schedule — using Celery's built-in timedelta schedule.
# django-celery-beat also supports crontab() if you prefer.
from celery.schedules import timedelta as celery_timedelta  # noqa: E402
CELERY_BEAT_SCHEDULE = {
    'update-hackathon-registration-statuses': {
        'task':     'organizer.tasks.update_hackathon_registration_statuses',
        'schedule': celery_timedelta(seconds=60),
    },
}
# Suppress "broker_connection_retry" deprecation warning in Celery 5.3+
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Windows: prefork pool doesn't support SIGUSR1 (soft timeouts).
# Use 'solo' in dev. Remove in production (Linux prefork works fine).
CELERY_WORKER_POOL = 'solo'
# ──────────────────────────────────────────────────────────────────────────────


ROOT_URLCONF = 'syntra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'syntra.wsgi.application'
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    FRONTEND_DIR / 'static',
]

# ── Media files (user uploads) ───────────────────────────────────────────────
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ── Social Auth (Google + GitHub OAuth) ──────────────────────────────────────
# 1. pip install social-auth-app-django
# 2. Uncomment 'social_django' in INSTALLED_APPS above
# 3. Uncomment the auth/ path in urls.py
# 4. Run: python manage.py migrate
# 5. Fill in credentials from Google Cloud Console / GitHub OAuth App

# AUTHENTICATION_BACKENDS = [
#     'social_core.backends.google.GoogleOAuth2',
#     'social_core.backends.github.GithubOAuth2',
#     'django.contrib.auth.backends.ModelBackend',
# ]
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY    = ''   # from .env
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''   # from .env
# SOCIAL_AUTH_GITHUB_KEY           = ''   # from .env
# SOCIAL_AUTH_GITHUB_SECRET        = ''   # from .env
# LOGIN_URL           = '/login/'
# LOGIN_REDIRECT_URL  = '/'
# LOGOUT_REDIRECT_URL = '/login/'
# ─────────────────────────────────────────────────────────────────────────────
