# Generated by Django 6.0.3 on 2026-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='max_teams_allowed',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of teams that can select this problem statement.'),
            preserve_default=False,
        ),
    ]
