# Generated by Django 5.0.14 on 2026-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_hackathon_hackathoncoordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_teams',
            field=models.IntegerField(default=0, help_text='Maximum number of teams allowed. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed')], default='upcoming', max_length=10),
        ),
    ]
