# Generated by Django 5.0.14 on 2026-04-20 15:35

import django.db.models.deletion
import organizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_add_registration_status_and_max_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(help_text='Upload a PDF file only.', upload_to=organizer.models.problem_pdf_upload_path, validators=[organizer.models.validate_pdf_file])),
                ('max_team_allowed', models.PositiveIntegerField(default=0, help_text='Maximum teams that can pick this problem. 0 = unlimited.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='organizer.hackathon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
