# Generated by Django 6.0.3 on 2026-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_hackathon_room_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('problem_selection', 'Problem Selection'), ('ongoing', 'Ongoing'), ('evaluation', 'Evaluation'), ('result_published', 'Result Published')], db_index=True, default='registration_open', max_length=30),
        ),
        migrations.AddIndex(
            model_name='problemstatement',
            index=models.Index(fields=['hackathon', 'is_active'], name='ps_hackathon_active_idx'),
        ),
    ]
