# Generated by Django 6.0.3 on 2026-05-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_perf_phase1_db_indexes'),
        ('participant', '0005_team_is_qr_active_team_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_categories', to='organizer.hackathon')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='organizer.scancategory')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_records', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='participant.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='organizer.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_hackathons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hackathon', 'user', 'is_active'], name='coord_h_u_active_idx')],
                'unique_together': {('hackathon', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='scancategory',
            index=models.Index(fields=['hackathon', 'is_active'], name='sc_h_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scancategory',
            unique_together={('hackathon', 'name')},
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['scan_category', 'team_member'], name='sr_cat_member_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scanrecord',
            unique_together={('team_member', 'scan_category')},
        ),
    ]
