# Generated by Django 6.0.3 on 2026-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_scancategory_scanrecord_hackathoncoordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('team', 'Team Wise'), ('participant', 'Participant Wise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
