# Generated by Django 5.2.6 on 2026-03-24 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('volunteers', 'Volunteers')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserOnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('preferred_role', models.CharField(blank=True, choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('volunteers', 'Volunteers')], max_length=20, null=True)),
                ('last_active_role', models.CharField(blank=True, choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('volunteers', 'Volunteers')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('github', 'GitHub')], max_length=20)),
                ('provider_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_identity_provider_per_user'), models.UniqueConstraint(condition=models.Q(('provider_user_id__isnull', False)), fields=('provider', 'provider_user_id'), name='unique_provider_subject')],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('volunteers', 'Volunteers')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role_assignment')],
            },
        ),
    ]
