# Generated by Django 6.0.3 on 2026-03-24 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_useronboardingprofile_authidentity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authidentity',
            name='unique_identity_provider_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='authidentity',
            name='unique_provider_subject',
        ),
        migrations.RemoveField(
            model_name='useronboardingprofile',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='userroleassignment',
            name='unique_user_role_assignment',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('volunteer', 'Volunteer'), ('super_admin', 'Super Admin')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='authidentity',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOnboardingProfile',
        ),
        migrations.RemoveField(
            model_name='userroleassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userroleassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthIdentity',
        ),
        migrations.DeleteModel(
            name='UserRoleAssignment',
        ),
    ]
