# Generated by Django 6.0.3 on 2026-04-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_problemstatement_max_teams_allowed'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='selected_problem_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_teams', to='organizer.problemstatement'),
        ),
    ]
