# Generated by Django 6.0.3 on 2026-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_team_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
