# Generated by Django 6.0.3 on 2026-05-18 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_invite_tokens(apps, schema_editor):
    Team = apps.get_model('participant', 'Team')

    for team in Team.objects.filter(invite_token__isnull=True):
        Team.objects.filter(pk=team.pk).update(invite_token=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_perf_phase1_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_team_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='participant.team')),
            ],
            options={
                'unique_together': {('team', 'receiver')},
            },
        ),
        migrations.RunPython(populate_invite_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
