# Generated by Django 6.0.3 on 2026-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_perf_phase1_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_qr_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='qr_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
