# Generated by Django 6.0.3

from django.db import migrations

def sync_leaders_to_members(apps, schema_editor):
    Team = apps.get_model('participant', 'Team')
    TeamMember = apps.get_model('participant', 'TeamMember')
    
    for team in Team.objects.filter(is_registered=True):
        leader = team.leader
        # Retrieve profile details if they exist
        # Note: Since ParticipantProfile might have a different relation or not be available directly via hasattr in apps models,
        # we can query ParticipantProfile from the apps registry.
        ParticipantProfile = apps.get_model('participant', 'ParticipantProfile')
        leader_profile = ParticipantProfile.objects.filter(user=leader).first()
        
        college = leader_profile.college if leader_profile else ""
        semester = leader_profile.semester if leader_profile else None
        degree = leader_profile.degree if leader_profile else ""
        
        # Sync leader into TeamMember if not already present
        TeamMember.objects.get_or_create(
            team=team,
            email=leader.email,
            defaults={
                'name': leader.full_name or leader.email,
                'college': college,
                'semester': semester,
                'degree': degree,
            }
        )

def reverse_sync_leaders_to_members(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_team_is_qr_active_team_qr_token'),
    ]

    operations = [
        migrations.RunPython(sync_leaders_to_members, reverse_sync_leaders_to_members),
    ]
